### ISSUE TITLE
Many icons not presented in minified CSS file in release

### ISSUE THREAD

**Issue by dzhuang** [marella/material-icons#43]
For example, I can't find `arrow_back` in `/css/material-icons.min.css` which was in `/css/material-icons.css` in release (and they were there in the repo).

**Comment by thomas5280** [comment]
See: https://github.com/dzhuang/subset-iconfont/issues/229

My summary of the issue is you're incorrectly outputting or parsing 'hyphenated' versions of icon names vs underscored names. I can't tell if this is a manual process you use in your CSS files, or if it's from an automated script.

My analysis:

_This is really interesting. I think it's an issue with "arrow_back" vs "arrow-back"

In their latest release in the ZIP file,
'arrow-back' appears to be present in the material-icons.min.css, but not "arrow_back"

But only "arrow_back" is in the code points file, and "arrow-back" is not there in the codepoints.json.

According to Google, the "arrow_back" is correct.
See: https://fonts.google.com/icons?icon.query=arrow_back&icon.set=Material+Icons

So this almost certainly seems to be a bug in a mismatch with hyphens vs underscores_

**Comment by marella** [comment]
This CSS is generated using Sass and `_` is replaced by `-` which can be changed using `$material-icons-css-replace` variable. Please see [README](https://github.com/marella/material-icons/tree/main/css#using-sass) if you are using Sass.

If you just need the list of icon names, you can use [`versions.json`](https://github.com/marella/material-icons/blob/main/_data/versions.json).

**Comment by dzhuang** [comment]
@marella Thanks for clarifying. I am closing this issue now.
